// export const FLAGS = {
//   "mmx": "Multimedia Extensions",
//   "fdiv": "FPU FDIV",
//   "coma": "Cyrix 6x86 coma",
//   "msr": "Model-Specific Registers"
// }
export const DEFAULT_QUERY = ""
export const FLAGS = {
  "FPU": "Onboard FPU",
  "VME": "Virtual Mode Extensions",
  "DE": "Debugging Extensions",
  "PSE": "Page Size Extensions",
  "TSC": "Time Stamp Counter",
  "PAE": "Physical Address Extensions",
  "MCE": "Machine Check Exception",
  "CX8": "CMPXCHG8 instruction",
  "APIC": "Onboard APIC",
  "MTRR": "Memory Type Range Registers",
  "PGE": "Page Global Enable",
  "MCA": "Machine Check Architecture",
  "PAT": "Page Attribute Table",
  "PN": "Processor serial number",
  "CLFLUSH": "CLFLUSH instruction",
  "ACPI": "ACPI via MSR",
  "MMX": "Multimedia Extensions",
  "PBE": "Pending Break Enable",
  "NX": "Execute Disable",
  "MMXEXT": "AMD MMX extensions",
  "RDTSCP": "RDTSCP",
  "RECOVERY": "CPU in recovery mode",
  "LONGRUN": "Longrun power control",
  "LRTI": "LongRun table interface",
  "CXMMX": "Cyrix MMX extensions",
  "K6_MTRR": "AMD K6 nonstandard MTRRs",
  "CONSTANT_TSC": "TSC ticks at a constant rate",
  "UP": "smp kernel running on up",
  "ARCH_PERFMON": "Intel Architectural PerfMon",
  "BTS": "Branch Trace Store",
  "REP_GOOD": "rep microcode works well",
  "XTOPOLOGY": "cpu topology enum extensions",
  "TSC_RELIABLE": "TSC is known to be reliable",
  "NONSTOP_TSC": "TSC does not stop in C states",
  "APERFMPERF": "APERFMPERF",
  "PCLMULQDQ": "PCLMULQDQ instruction",
  "VMX": "Hardware virtualization",
  "SMX": "Safer mode",
  "EST": "Enhanced SpeedStep",
  "TM2": "Thermal Monitor 2",
  "CID": "Context ID",
  "CX16": "CMPXCHG16B",
  "XTPR": "Send Task Priority Messages",
  "PDCM": "Performance Capabilities",
  "PCID": "Process Context Identifiers",
  "DCA": "Direct Cache Access",
  "X2APIC": "x2APIC",
  "MOVBE": "MOVBE instruction",
  "POPCNT": "POPCNT instruction",
  "TSC_DEADLINE_TIMER": "Tsc deadline timer",
  "AES": "AES instructions",
  "AVX": "Advanced Vector Extensions",
  "RDRAND": "The RDRAND instruction",
  "HYPERVISOR": "Running on a hypervisor",
  "ACE2": "Advanced Cryptography Engine v2",
  "ACE2_EN": "ACE v2 enabled",
  "PHE": "PadLock Hash Engine",
  "PHE_EN": "PHE enabled",
  "PMM": "PadLock Montgomery Multiplier",
  "PMM_EN": "PMM enabled",
  "CMP_LEGACY": "If yes HyperThreading not valid",
  "SVM": "Secure virtual machine",
  "EXTAPIC": "Extended APIC space",
  "ABM": "Advanced bit manipulation",
  "MISALIGNSSE": "Misaligned SSE mode",
  "3DNOWPREFETCH": "3DNow prefetch instructions",
  "OSVW": "OS Visible Workaround",
  "IBS": "Instruction Based Sampling",
  "XOP": "extended AVX instructions",
  "WDT": "Watchdog timer",
  "LWP": "Light Weight Profiling",
  "FMA4": "4 operands MAC instructions",
  "TCE": "translation cache extension",
  "NODEID_MSR": "NodeId MSR",
  "TBM": "trailing bit manipulations",
  "TOPOEXT": "topology extensions CPUID leafs",
  "PERFCTR_CORE": "core performance counter extensions",
  "PERFCTR_NB": "NB performance counter extensions",
  "BPEXT": "data breakpoint extension",
  "PERFCTR_L2": "L2 performance counter extensions",
  "IDA": "Intel Dynamic Acceleration",
  "ARAT": "Always Running APIC Timer",
  "CPB": "AMD Core Performance Boost",
  "EPB": "IA32_ENERGY_PERF_BIAS support",
  "PLN": "Intel Power Limit Notification",
  "PTS": "Intel Package Thermal Status",
  "DTHERM": "Digital Thermal Sensor",
  "PROC_FEEDBACK": "AMD ProcFeedbackInterface",
  "HWP_NOITFY": "Intel HWP_NOTIFY",
  "HWP_ACT_WINDOW": "Intel HWP_ACT_WINDOW",
  "HWP_EPP": "Intel HWP_EPP",
  "HWP_PKG_REQ": "Intel HWP_PKG_REQ",
  "INTEL_PT": "Intel Processor Trace",
  "TPR_SHADOW": "Intel TPR Shadow",
  "VNMI": "Intel Virtual NMI",
  "FLEXPRIORITY": "Intel FlexPriority",
  "EPT": "Intel Extended Page Table",
  "VPID": "Intel Virtual Processor ID",
  "NPT": "AMD Nested Page Table support",
  "LBRV": "AMD LBR Virtualization support",
  "DECODEASSISTS": "AMD Decode Assists support",
  "PAUSEFILTER": "AMD filtered pause intercept",
  "PFTHRESHOLD": "AMD pause filter threshold",
  "VMMCALL": "Prefer vmmcall to vmcall",
  "TSC_ADJUST": "TSC adjustment MSR 0x3b",
  "BMI1": "1st group bit manipulation extensions",
  "HLE": "Hardware Lock Elision",
  "AVX2": "AVX2 instructions",
  "SMEP": "Supervisor Mode Execution Protection",
  "BMI2": "2nd group bit manipulation extensions",
  "INVPCID": "Invalidate Processor Context ID",
  "RTM": "Restricted Transactional Memory",
  "CQM": "Cache QoS Monitoring",
  "MPX": "Memory Protection Extension",
  "RDSEED": "The RDSEED instruction",
  "ADX": "The ADCX and ADOX instructions",
  "SMAP": "Supervisor Mode Access Prevention",
  "PCOMMIT": "PCOMMIT instruction",
  "CLFLUSHOPT": "CLFLUSHOPT instruction",
  "CLWB": "CLWB instruction",
  "XSAVEOPT": "XSAVEOPT",
  "XSAVEC": "XSAVEC",
  "CQM_LLC": "LLC QoS if 1",
  "CQM_OCCUP_LLC": "LLC occupancy monitoring if 1",
  "F00F": "Intel F00F",
  "FDIV": "FPU FDIV",
  "COMA": "Cyrix 6x86 coma",
  "11AP": "Bad local APIC aka 11AP"
}
